
export const shopsData = [
  { id: 1, name: "Aura Fashion", category: "Одежда", floor: 1, logo: "https://placehold.co/200x100.png", hint: "fashion logo", description: "Высокая мода для современных женщин. Откройте для себя эксклюзивные коллекции от ведущих мировых дизайнеров. Мы предлагаем платья, костюмы, верхнюю одежду и аксессуары, которые подчеркнут ваш уникальный стиль.", images: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png", "https://placehold.co/600x400.png"], promotions: ["Скидка 20% на новые поступления"] },
  { id: 2, name: "Sole Mates", category: "Обувь", floor: 2, logo: "https://placehold.co/200x100.png", hint: "shoe logo", description: "Последние тенденции в мире обуви для мужчин и женщин. От классических моделей до спортивных кроссовок – у нас есть все, чтобы вы чувствовали себя комфортно и уверенно.", images: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png", "https://placehold.co/600x400.png", "https://placehold.co/600x400.png", "https://placehold.co/600x400.png"], promotions: ["Купи одну пару, получи вторую со скидкой 50%"] },
  { id: 3, name: "TechVerse", category: "Электроника", floor: 1, logo: "https://placehold.co/200x100.png", hint: "tech logo", description: "Гаджеты и аксессуары для вашей цифровой жизни. Новейшие смартфоны, ноутбуки, наушники и умные устройства от ведущих брендов. Наши консультанты помогут вам сделать правильный выбор.", images: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png", "https://placehold.co/600x400.png"], promotions: [] },
  { id: 4, name: "Glamour Zone", category: "Красота", floor: 2, logo: "https://placehold.co/200x100.png", hint: "beauty logo", description: "Все для вашей красоты: косметика, уход за кожей и парфюмерия от люксовых и нишевых брендов. Профессиональные визажисты всегда готовы дать вам совет.", images: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png"], promotions: ["Подарок при покупке от 50$"] },
  { id: 5, name: "Book Nook", category: "Книги", floor: 3, logo: "https://placehold.co/200x100.png", hint: "bookstore logo", description: "Уютный уголок для любителей книг. У нас вы найдете бестселлеры, классику, детскую литературу и редкие издания. Наслаждайтесь чтением в нашей комфортной зоне отдыха.", images: ["https://placehold.co/600x400.png"], promotions: [] },
  { id: 6, name: "Zenith Watches", category: "Ювелирные изделия", floor: 1, logo: "https://placehold.co/200x100.png", hint: "watch logo", description: "Роскошные часы и изысканные украшения для особых моментов. Мы являемся официальным дилером всемирно известных часовых и ювелирных мануфактур.", images: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png", "https://placehold.co/600x400.png", "https://placehold.co/600x400.png"], promotions: ["Бесплатная чистка в подарок"] },
  { id: 7, "name": "Vogue Apparel", "category": "Одежда", "floor": 2, "logo": "https://placehold.co/200x100.png", hint: "clothing logo", "description": "Модная и доступная одежда для всех. Мы следим за последними трендами и еженедельно обновляем наши коллекции, чтобы вы всегда выглядели стильно.", "images": ["https://placehold.co/600x400.png"], "promotions": ["Скидка 15% для студентов"] },
  { id: 8, "name": "Step Up", "category": "Обувь", "floor": 1, "logo": "https://placehold.co/200x100.png", hint: "sneaker logo", "description": "Спортивная и повседневная обувь для всей семьи. У нас вы найдете идеальную пару для бега, тренировок или просто для активного отдыха.", "images": ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png"], "promotions": [] }
];

export const categories = ["Все", ...Array.from(new Set(shopsData.map((s) => s.category)))];
export const floors = ["Все", ...Array.from(new Set(shopsData.map((s) => s.floor.toString())))].sort();
