
export const shopsData = [
  { id: 1, name: "Kari", category: "Обувь и одежда", floor: 1, logo: "https://placehold.co/200x100.png", hint: "shoe logo", description: "Модная и доступная обувь для всей семьи. Откройте для себя нашу новую коллекцию.", images: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png"], promotions: ["Скидка 20% на новые поступления"], workingHours: "10:00 - 22:00", phone: "(123) 555-1010" },
  { id: 2, name: "ANITA", category: "Одежда", floor: 1, logo: "https://placehold.co/200x100.png", hint: "fashion logo", description: "Стильная женская одежда на любой случай. Откройте для себя последние тренды.", images: ["https://placehold.co/600x400.png"], promotions: [], workingHours: "10:00 - 22:00", phone: "(123) 555-2020" },
  { id: 4, name: "НАПРОТИФ", category: "Магазин одежды", floor: 1, logo: "https://placehold.co/200x100.png", hint: "clothing store", description: "Магазин современной одежды для мужчин и женщин. Всегда актуальные коллекции.", images: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png"], promotions: ["Подарок при покупке от 50$"], workingHours: "10:00 - 22:00", phone: "(123) 555-4040" },
  { id: 5, name: "TREND", category: "Женская одежда", floor: 1, logo: "https://placehold.co/200x100.png", hint: "fashion logo", description: "Женская одежда, отражающая последние модные тенденции.", images: ["https://placehold.co/600x400.png"], promotions: [], workingHours: "11:00 - 20:00", phone: "(123) 555-5050" },
  { id: 6, name: "АВТОКАССЫ", category: "Продажа билетов", floor: 1, logo: "https://placehold.co/200x100.png", hint: "ticket office", description: "Продажа билетов на междугородние автобусы.", images: ["https://placehold.co/600x400.png"], promotions: [], workingHours: "08:00 - 20:00", phone: "(123) 555-6060" },
  { id: 7, name: "ДЖИНСЫ+", category: "Магазин одежды", floor: 1, logo: "https://placehold.co/200x100.png", hint: "jeans logo", description: "Широкий выбор джинсовой одежды для всех возрастов.", images: ["https://placehold.co/600x400.png"], promotions: ["Скидка 15% для студентов"], workingHours: "10:00 - 22:00", phone: "(123) 555-7070" },
  { id: 8, name: "РосМех", category: "Одежда", floor: 1, logo: "https://placehold.co/200x100.png", hint: "fur logo", description: "Изделия из натурального меха от российского производителя.", images: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png"], promotions: [], workingHours: "10:00 - 21:00", phone: "(123) 555-8080" },
  { id: 9, name: "Лидер", category: "Спортивные товары", floor: 1, logo: "https://placehold.co/200x100.png", hint: "sportswear logo", description: "Спортивная одежда и инвентарь для активного образа жизни.", images: ["https://placehold.co/600x400.png"], promotions: [], workingHours: "10:00 - 22:00", phone: "(123) 555-9090" },
  { id: 10, name: "ONYX", category: "Ювелирный магазин", floor: 1, logo: "https://placehold.co/200x100.png", hint: "jewelry logo", description: "Эксклюзивные ювелирные украшения из драгоценных металлов и камней.", images: ["https://placehold.co/600x400.png"], promotions: ["Скидка 10% на обручальные кольца"], workingHours: "10:00 - 21:00", phone: "(123) 555-1111" },
  { id: 11, name: "Галатея", category: "Магазин одежды", floor: 1, logo: "https://placehold.co/200x100.png", hint: "fashion store", description: "Магазин элегантной женской одежды.", images: ["https://placehold.co/600x400.png"], promotions: [], workingHours: "10:00 - 22:00", phone: "(123) 555-1212" },
  { id: 12, name: "ИренА", category: "Магазин одежды", floor: 1, logo: "https://placehold.co/200x100.png", hint: "fashion store", description: "Стильная одежда для создания вашего неповторимого образа.", images: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png"], promotions: [], workingHours: "10:00 - 22:00", phone: "(123) 555-1313" },
  { id: 13, name: "Веселая затея", category: "Для праздника", floor: 1, logo: "https://placehold.co/200x100.png", hint: "party supplies", description: "Все для вашего праздника: воздушные шары, украшения, карнавальные костюмы.", images: ["https://placehold.co/600x400.png"], promotions: [], workingHours: "10:00 - 20:00", phone: "(123) 555-1414" },
  { id: 14, name: "Время есть", category: "Кафе/рестораны", floor: 1, logo: "https://placehold.co/200x100.png", hint: "cafe logo", description: "Уютное кафе с домашней кухней и свежей выпечкой.", images: ["https://placehold.co/600x400.png"], promotions: ["Бизнес-ланч по будням"], workingHours: "09:00 - 21:00", phone: "(123) 555-1515" },
  { id: 16, name: "БЕГЕМОТиК", category: "Детский магазин", floor: 1, logo: "https://placehold.co/200x100.png", hint: "kids store", description: "Сеть магазинов игрушек и товаров для детей.", images: ["https://placehold.co/600x400.png"], promotions: [], workingHours: "10:00 - 21:00", phone: "(123) 555-1616" },
  { id: 17, name: "Дамские штучки", category: "Одежда", floor: 1, logo: "https://placehold.co/200x100.png", hint: "lingerie logo", description: "Изысканное нижнее белье и домашняя одежда для женщин.", images: ["https://placehold.co/600x400.png"], promotions: [], workingHours: "10:00 - 22:00", phone: "(123) 555-1717" },
  { id: 18, name: "Буквоед", category: "Книги", floor: 1, logo: "https://placehold.co/200x100.png", hint: "bookstore logo", description: "Книжный магазин с широким выбором литературы и канцтоваров.", images: ["https://placehold.co/600x400.png"], promotions: [], workingHours: "10:00 - 22:00", phone: "(123) 555-1818" },
  { id: 21, name: "FOROOM", category: "Для дома", floor: 1, logo: "https://placehold.co/200x100.png", hint: "home goods", description: "Все для уюта в вашем доме: декор, посуда, текстиль.", images: ["https://placehold.co/600x400.png"], promotions: [], workingHours: "10:00 - 21:00", phone: "(123) 555-2222" },
  { id: 22, name: "DNS", category: "Цифровая техника", floor: 1, logo: "https://placehold.co/200x100.png", hint: "tech logo", description: "Магазин цифровой и бытовой техники. Широкий ассортимент и доступные цены.", images: ["https://placehold.co/600x400.png"], promotions: [], workingHours: "10:00 - 22:00", phone: "(123) 555-2323" },
  { id: 23, name: "Все инструменты.ру", category: "Инструменты", floor: 1, logo: "https://placehold.co/200x100.png", hint: "tools logo", description: "Профессиональный инструмент и оборудование для строительства и ремонта.", images: ["https://placehold.co/600x400.png"], promotions: [], workingHours: "09:00 - 20:00", phone: "(123) 555-2424" },
  { id: 24, name: "Восторг", category: "Подарки", floor: 2, logo: "https://placehold.co/200x100.png", hint: "gift shop", description: "Магазин удивительных подарков и сувениров.", images: ["https://placehold.co/600x400.png"], promotions: [], workingHours: "10:00 - 22:00", phone: "(123) 555-2525" }
];

export const categories = ["Все", ...Array.from(new Set(shopsData.map((s) => s.category)))];
export const floors = ["Все", ...Array.from(new Set(shopsData.map((s) => s.floor.toString())))].sort();
